name: CI
on:
  workflow_run:
    workflows: ["style", "tests", "docs", "build"]
    types:
      - completed

jobs:

  release:
    name: Release
    if: |
      github.event_name == 'push' &&
      contains(github.ref, 'refs/tags') && 
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build wine

      - name: Build artifacts
        run: |
          python -m build && python -m twine check dist/*

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m twine upload --skip-existing ./**/*.whl
          python -m twine upload --skip-existing ./**/*.tar.gz

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./**/*.whl
            ./**/*.tar.gz
