name: CI
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  MAIN_PYTHON_VERSION: '3.10'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: "Test library"
    runs-on: ${{ matrix.os }}
    strategy:
       matrix:
         os: [windows-latest, macos-latest, ubuntu-latest]
         python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:

      - name: "Run pytest in ${{ matrix.os }}-python-${{ matrix.python-version }}"
        uses: pyansys/actions/tests-pytest@v1
        with:
          pytest-markers: "-k 'mocked'"
          pytest-extra-args: "--cov=ansys.<library> --cov-report=term --cov-report=xml:.cov/coverage.xml --cov-report=html:.cov/html"
          pytest-postargs: "tests -vv"

      - name: "Upload Coverage Results"
        uses: actions/upload-artifact@v3
        if: matrix.python-version == ${{ env.MAIN_PYTHON_VERSION }}
        with:
          name: coverage-html
          path: .cov/html
          retention-days: 7
