name: CI
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
      fail-fast: false

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          <additional dependencies>

      - name: Run tests
        run: |
          <command for running your tests>

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        if: matrix.python-version == '3.9'
