name: CI

on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  MAIN_PYTHON_VERSION: '3.10'
  DOCUMENTATION_CNAME: 'dev.docs.pyansys.com'
  MEILISEARCH_API_KEY: ${{ secrets.MEILISEARCH_API_KEY }}
  MEILISEARCH_PUBLIC_API_KEY: ${{ secrets.MEILISEARCH_PUBLIC_API_KEY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:

  # TODO: Uncomment when ansys/actions/doc-style@v5 works with single back ticks
  doc-style:
    name: "Check documentation style"
    runs-on: ubuntu-latest
    steps:
      - name: "Check documentation style"
        uses: ansys/actions/doc-style@test/vale-no-exit
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          vale-version: "3.3.0"