name: Nightly Documentation Build

on:
  schedule:  # UTC at 0400
    - cron:  '0 4 * * */2' # To run every 3 days
  workflow_dispatch:

env:
  MAIN_PYTHON_VERSION: '3.10'

jobs:
  nightly-docs:
    name: Nightly documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb texlive-latex-extra latexmk nodejs npm graphviz
          npm install -g @mermaid-js/mermaid-cli

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip tox

      - name: Build HTML documentation
        run: |
          xvfb-run tox -e doc

      - name: Build PDF Documentation
        run: |
          sudo apt update
          sudo apt-get install -y texlive-latex-extra latexmk
          python -m pip install -r requirements/requirements_doc.txt
          make -C doc pdf

      - name: Upload HTML documentation
        uses: actions/upload-artifact@v3.1.3
        with:
          name: HTML-Documentation
          path: .tox/doc_out_html/
          retention-days: 7

      - name: Upload PDF Documentation
        uses: actions/upload-artifact@v3.1.3
        with:
          name: PDF-Documentation
          path: doc/build/latex/pyansys*.pdf
          retention-days: 7

      - name: Deploy to gh-pages
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .tox/doc_out_html/
          CLEAN: true
          SINGLE_COMMIT: true
